name: Cross-Platform CI for SocialMediaApp

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Debug environment
        run: |
          echo "Current directory:"
          pwd
          echo "Files in directory:"
          ls -al
          echo "Python version:"
          python --version

      - name: Run tests
        run: pytest test_app.py
